# Generated by Django 5.0.14 on 2025-05-20 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProducto',
            fields=[
                ('id_categoria', models.AutoField(db_column='IDCategoria', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, db_column='Nombre', max_length=100, null=True)),
                ('descripcion', models.CharField(blank=True, db_column='Descripcion', max_length=255, null=True)),
            ],
            options={
                'db_table': 'CategoriaProducto',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(db_column='IDCliente', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, db_column='Nombre', max_length=100, null=True)),
                ('nit', models.CharField(blank=True, db_column='NIT', max_length=20, null=True)),
                ('telefono', models.CharField(blank=True, db_column='Telefono', max_length=20, null=True)),
                ('direccion', models.CharField(blank=True, db_column='Direccion', max_length=255, null=True)),
            ],
            options={
                'db_table': 'Cliente',
            },
        ),
        migrations.CreateModel(
            name='CuentaContable',
            fields=[
                ('id_cuenta', models.AutoField(db_column='IDCuenta', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, db_column='Nombre', max_length=100, null=True)),
                ('tipo', models.CharField(blank=True, db_column='Tipo', max_length=50, null=True)),
                ('codigo', models.CharField(blank=True, db_column='Codigo', max_length=20, null=True)),
            ],
            options={
                'db_table': 'CuentaContable',
            },
        ),
        migrations.CreateModel(
            name='IngresoInventario',
            fields=[
                ('id_ingreso', models.AutoField(db_column='IDIngreso', primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(blank=True, db_column='Fecha', null=True)),
                ('proveedor', models.IntegerField(blank=True, db_column='IDProveedor', null=True)),
            ],
            options={
                'db_table': 'IngresoInventario',
            },
        ),
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id_permiso', models.AutoField(db_column='IDPermiso', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, db_column='Nombre', max_length=100, null=True)),
            ],
            options={
                'db_table': 'Permiso',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(db_column='IDRol', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, db_column='Nombre', max_length=100, null=True)),
            ],
            options={
                'db_table': 'Rol',
            },
        ),
        migrations.CreateModel(
            name='TransaccionContable',
            fields=[
                ('id_transaccion', models.AutoField(db_column='IDTransaccion', primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(blank=True, db_column='Fecha', null=True)),
                ('descripcion', models.CharField(blank=True, db_column='Descripcion', max_length=255, null=True)),
                ('monto_total', models.DecimalField(blank=True, db_column='MontoTotal', decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'TransaccionContable',
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id_factura', models.AutoField(db_column='IDFactura', primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(blank=True, db_column='Fecha', null=True)),
                ('total', models.DecimalField(blank=True, db_column='Total', decimal_places=2, max_digits=10, null=True)),
                ('forma_pago', models.CharField(blank=True, db_column='FormaPago', max_length=50, null=True)),
                ('cliente', models.ForeignKey(blank=True, db_column='IDCliente', null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.cliente')),
            ],
            options={
                'db_table': 'Factura',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(db_column='IDProducto', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, db_column='Nombre', max_length=100, null=True)),
                ('descripcion', models.CharField(blank=True, db_column='Descripcion', max_length=255, null=True)),
                ('precio_compra', models.DecimalField(blank=True, db_column='PrecioCompra', decimal_places=2, max_digits=10, null=True)),
                ('precio_venta', models.DecimalField(blank=True, db_column='PrecioVenta', decimal_places=2, max_digits=10, null=True)),
                ('stock', models.IntegerField(blank=True, db_column='Stock', null=True)),
                ('unidad_medida', models.CharField(blank=True, db_column='UnidadMedida', max_length=50, null=True)),
                ('categoria', models.ForeignKey(blank=True, db_column='IDCategoria', null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.categoriaproducto')),
            ],
            options={
                'db_table': 'Producto',
            },
        ),
        migrations.CreateModel(
            name='DetalleIngresoInventario',
            fields=[
                ('id_detalle', models.AutoField(db_column='IDDetalle', primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(blank=True, db_column='Cantidad', null=True)),
                ('precio_compra', models.DecimalField(blank=True, db_column='PrecioCompra', decimal_places=2, max_digits=10, null=True)),
                ('ingreso', models.ForeignKey(blank=True, db_column='IDIngreso', null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.ingresoinventario')),
                ('producto', models.ForeignKey(blank=True, db_column='IDProducto', null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.producto')),
            ],
            options={
                'db_table': 'DetalleIngresoInventario',
            },
        ),
        migrations.CreateModel(
            name='DetalleFactura',
            fields=[
                ('id_detalle', models.AutoField(db_column='IDDetalle', primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(blank=True, db_column='Cantidad', null=True)),
                ('precio_unitario', models.DecimalField(blank=True, db_column='PrecioUnitario', decimal_places=2, max_digits=10, null=True)),
                ('factura', models.ForeignKey(blank=True, db_column='IDFactura', null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.factura')),
                ('producto', models.ForeignKey(blank=True, db_column='IDProducto', null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.producto')),
            ],
            options={
                'db_table': 'DetalleFactura',
            },
        ),
        migrations.CreateModel(
            name='DetalleTransaccionContable',
            fields=[
                ('id_detalle', models.AutoField(db_column='IDDetalle', primary_key=True, serialize=False)),
                ('monto', models.DecimalField(blank=True, db_column='Monto', decimal_places=2, max_digits=10, null=True)),
                ('tipo', models.CharField(blank=True, db_column='Tipo', max_length=10, null=True)),
                ('cuenta', models.ForeignKey(blank=True, db_column='IDCuenta', null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.cuentacontable')),
                ('transaccion', models.ForeignKey(blank=True, db_column='IDTransaccion', null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.transaccioncontable')),
            ],
            options={
                'db_table': 'DetalleTransaccionContable',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(db_column='IDUsuario', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, db_column='Nombre', max_length=100, null=True)),
                ('username', models.CharField(blank=True, db_column='Username', max_length=50, null=True)),
                ('email', models.CharField(blank=True, db_column='Email', max_length=100, null=True)),
                ('password_hash', models.CharField(blank=True, db_column='PasswordHash', max_length=255, null=True)),
                ('rol', models.ForeignKey(blank=True, db_column='IDRol', null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.rol')),
            ],
            options={
                'db_table': 'Usuario',
            },
        ),
        migrations.AddField(
            model_name='ingresoinventario',
            name='usuario_registro',
            field=models.ForeignKey(blank=True, db_column='UsuarioRegistro', null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.usuario'),
        ),
        migrations.AddField(
            model_name='factura',
            name='usuario',
            field=models.ForeignKey(blank=True, db_column='IDUsuario', null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.usuario'),
        ),
        migrations.CreateModel(
            name='RolPermiso',
            fields=[
                ('rol', models.ForeignKey(db_column='IDRol', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='inventario.rol')),
                ('permiso', models.ForeignKey(db_column='IDPermiso', on_delete=django.db.models.deletion.CASCADE, to='inventario.permiso')),
            ],
            options={
                'db_table': 'RolPermiso',
                'unique_together': {('rol', 'permiso')},
            },
        ),
    ]
